### ISSUE TITLE
pickup generated ssh public keys from other instances and template them to authorized_keys

### ISSUE THREAD

**Issue by p-thurner** [blunix/role-ssh#13]
pickup generated ssh public keys from other instances and template them to authorized_keys

**Comment by p-thurner** [comment]
like

```
- name: fetch the backuppc ssh public key
  shell: "cat /var/lib/backuppc/.ssh/id_ed25519.pub"
  register: backuppc_server_ssh_public_key_for_clients
  delegate_to: "{{ backuppc_client_backup_host }}"

- name: setup the backuppc ssh public key
  authorized_key:
    user: root
    state: present
    key: "{{ backuppc_server_ssh_public_key_for_clients.stdout }}"
  ignore_errors: "{{ ansible_check_mode }}"
```
